// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHb7sxpZs6fDz04dCx77Ct_NpD3ZWx_rA',
    appId: '1:1012761819888:web:b5e36f97d9ed831fea6035',
    messagingSenderId: '1012761819888',
    projectId: 'lendme-bad05',
    authDomain: 'lendme-bad05.firebaseapp.com',
    storageBucket: 'lendme-bad05.firebasestorage.app',
    measurementId: 'G-J9QSCSZZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhMWYj7FTGiZtHW-DccL_0yQTKW1R8hoY',
    appId: '1:1012761819888:android:345149b1bdcb3bb9ea6035',
    messagingSenderId: '1012761819888',
    projectId: 'lendme-bad05',
    storageBucket: 'lendme-bad05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSotXpMOyVyvtLp0NVAFY2In47LCUMYWc',
    appId: '1:1012761819888:ios:3eb68224f15fe0ccea6035',
    messagingSenderId: '1012761819888',
    projectId: 'lendme-bad05',
    storageBucket: 'lendme-bad05.firebasestorage.app',
    iosBundleId: 'com.example.lendme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSotXpMOyVyvtLp0NVAFY2In47LCUMYWc',
    appId: '1:1012761819888:ios:3eb68224f15fe0ccea6035',
    messagingSenderId: '1012761819888',
    projectId: 'lendme-bad05',
    storageBucket: 'lendme-bad05.firebasestorage.app',
    iosBundleId: 'com.example.lendme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHb7sxpZs6fDz04dCx77Ct_NpD3ZWx_rA',
    appId: '1:1012761819888:web:d01a720610e88e91ea6035',
    messagingSenderId: '1012761819888',
    projectId: 'lendme-bad05',
    authDomain: 'lendme-bad05.firebaseapp.com',
    storageBucket: 'lendme-bad05.firebasestorage.app',
    measurementId: 'G-N4XP9GVVG5',
  );
}
